// Bump this whenever the Terms or Privacy Policy text changes below --
// every user (new and existing) must re-agree before using the app again.
// See src/app/dashboard/layout.tsx and src/app/onboarding/layout.tsx for
// the gate that enforces this, and src/app/api/auth/accept-terms/route.ts
// for the endpoint that records a fresh agreement.
export const CURRENT_TERMS_VERSION = 1;

export const OPERATOR_NAME = "Aayush Patel";
export const CONTACT_EMAIL = "aayushp1123@gmail.com";
export const GOVERNING_LAW_STATE = "Pennsylvania";
export const LAST_UPDATED = "August 18, 2026";

export interface LegalSection {
  heading: string;
  paragraphs: string[];
}

export const TERMS_SECTIONS: LegalSection[] = [
  {
    heading: "1. What Portfolio Watcher Is",
    paragraphs: [
      `Portfolio Watcher is a personal investing dashboard operated by ${OPERATOR_NAME} as an individual, not a company. It links to your brokerage account (via Plaid) and generates AI-written reports about your holdings, market trends, and news.`,
      "The app and account creation are free, and always will be. There is no payment processing anywhere in this app.",
    ],
  },
  {
    heading: "2. Not Financial Advice",
    paragraphs: [
      "Every rating, risk assessment, allocation suggestion, and piece of commentary in this app is generated by an AI model reasoning over live market data. None of it is financial, investment, tax, or legal advice, and none of it is a recommendation to buy, hold, or sell any security.",
      "The AI can be wrong, incomplete, or out of date. You are solely responsible for your own investment decisions. Always do your own research and consult a licensed financial professional before acting on anything in this app.",
    ],
  },
  {
    heading: "3. Your Account",
    paragraphs: [
      "You must provide accurate information when creating an account and are responsible for keeping your password (and, if enabled, your two-factor authentication device) secure. You're responsible for all activity that happens under your account.",
      "You may delete your account at any time from Settings, which permanently removes your data as described in the Privacy Policy's Data Deletion section.",
    ],
  },
  {
    heading: "4. Acceptable Use",
    paragraphs: [
      "Use the app only for its intended purpose: tracking and researching your own investments. Don't attempt to access another user's account or data, disrupt or overload the service, scrape or resell the AI-generated content, or use the app for any unlawful purpose.",
    ],
  },
  {
    heading: "5. LIMITATION OF LIABILITY",
    paragraphs: [
      "THE APP AND ALL REPORTS, RATINGS, AND CONTENT IT GENERATES ARE PROVIDED \"AS IS\" AND \"AS AVAILABLE,\" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF ACCURACY, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.",
      `TO THE MAXIMUM EXTENT PERMITTED BY LAW, ${OPERATOR_NAME.toUpperCase()} WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR ANY INVESTMENT LOSSES, TRADING LOSSES, OR LOST PROFITS ARISING FROM YOUR USE OF THE APP OR RELIANCE ON ANY REPORT IT GENERATES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.`,
      "TOTAL LIABILITY FOR ANY CLAIM RELATED TO THE APP IS CAPPED AT THE GREATER OF (A) $0, OR (B) THE TOTAL AMOUNT YOU PAID TO USE THE APP IN THE 12 MONTHS BEFORE THE CLAIM AROSE. BECAUSE THE APP IS FREE, THIS CAP IS CURRENTLY $0.",
    ],
  },
  {
    heading: "6. Indemnification",
    paragraphs: [
      `You agree to indemnify and hold ${OPERATOR_NAME} harmless from any claim, loss, liability, or expense (including reasonable legal fees) arising out of your use of the app, your violation of these Terms, or your violation of any right of a third party, including any investment decision you make based on the app's content.`,
    ],
  },
  {
    heading: "7. Termination",
    paragraphs: [
      "Your account may be suspended or terminated for violating these Terms, or the app may be discontinued at any time, without liability. You may stop using the app and delete your account whenever you'd like.",
    ],
  },
  {
    heading: "8. Changes to These Terms",
    paragraphs: [
      "These Terms may be updated from time to time. When they change in a meaningful way, every user — new or existing — is required to review and re-agree to the updated version before continuing to use the app.",
    ],
  },
  {
    heading: "9. Governing Law",
    paragraphs: [
      `These Terms are governed by the laws of the Commonwealth of ${GOVERNING_LAW_STATE}, without regard to its conflict-of-laws principles, regardless of where you access the app from.`,
    ],
  },
  {
    heading: "10. Contact",
    paragraphs: [`Questions about these Terms can be sent to ${CONTACT_EMAIL}.`],
  },
];

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    heading: "1. What We Collect",
    paragraphs: [
      "Account info you provide directly: email, name (optional), and a hashed password (never stored in plain text).",
      "Brokerage data, only if you choose to connect an account via Plaid: your holdings, balances, and transaction history, retrieved through Plaid's API. Your Plaid access token is encrypted at rest.",
      "Anything else you enter yourself: watchlist tickers, financial goals, and exit rules you set up.",
      "Usage data needed to run the app: when reports were generated, and which AI model produced them.",
    ],
  },
  {
    heading: "2. How We Use It",
    paragraphs: [
      "Solely to run the app for you: generating your reports, showing your dashboard, and sending you the data you've asked to see. Your data is never sold, rented, or shared with advertisers, and there are no ad trackers or analytics-for-profit in this app.",
      "Your holdings and goals are sent to Google's Gemini API (and, for a small pilot feature, Groq's API) so it can write your reports. See each provider's own privacy policy for how they handle data sent to their API.",
    ],
  },
  {
    heading: "3. Data Deletion",
    paragraphs: [
      "You can permanently delete your account and all associated data at any time from Settings → Delete Account. This immediately and irreversibly removes your account, holdings cache, reports, goals, exit rules, watchlist, and any linked Plaid connection.",
      `If you'd rather not use the in-app option, email ${CONTACT_EMAIL} and your account will be deleted within a reasonable time.`,
    ],
  },
  {
    heading: "4. Data Security",
    paragraphs: [
      "Passwords are hashed (never stored in plain text). Plaid access tokens are encrypted at rest with AES-256-GCM. Two-factor authentication is available and recommended.",
    ],
  },
  {
    heading: "5. Third-Party Services",
    paragraphs: [
      "Plaid (brokerage linking), Google Gemini and Groq (AI report generation), and standard free financial data sources (e.g. SEC EDGAR, FRED) that the app queries on your behalf. None of these receive more of your data than is needed to perform their specific function.",
    ],
  },
  {
    heading: "6. Changes to This Policy",
    paragraphs: [
      "When this policy changes in a meaningful way, every user — new or existing — is required to review and re-agree to the updated version before continuing to use the app.",
    ],
  },
  {
    heading: "7. Governing Law",
    paragraphs: [
      `This policy is governed by the laws of the Commonwealth of ${GOVERNING_LAW_STATE}, without regard to its conflict-of-laws principles, regardless of where you access the app from.`,
    ],
  },
  {
    heading: "8. Contact",
    paragraphs: [`Questions about this policy, or a data deletion request, can be sent to ${CONTACT_EMAIL}.`],
  },
];
